

export const GET_DATA_LOADING = "GET_DATA_LOADING";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";

export const DETAILS_DATA_LOADING = "DETAILS_DATA_LOADING";
export const DETAILS_DATA_SUCCESS = "DETAILS_DATA_SUCCESS";

export const CART_DATA_LOADING = "CART_DATA_LOADING";
export const CART_DATA_SUCCESS = "CART_DATA_SUCCESS";